# Generated by Django 5.2.1 on 2026-03-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAssociation',
            fields=[
                ('associationId', models.AutoField(primary_key=True, serialize=False)),
                ('frequency', models.IntegerField(default=1)),
                ('associationPercentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('totalProduct1Purchases', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('product1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_from', to='api.product')),
                ('product2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associations_to', to='api.product')),
            ],
            options={
                'unique_together': {('product1', 'product2')},
            },
        ),
    ]
